name: inception

services:
  mariadb:
    container_name: mariadb
    image: mariadb:1
    build: requirements/mariadb
    volumes:
      - database:/var/log/mariadb
    networks:
      - database
    secrets:
      - database_name
      - database_user_name
      - database_user_password
    env_file: .env
    restart: always
  nginx:
    container_name: nginx
    image: nginx:1
    build: requirements/nginx
    networks:
      - web
    ports:
      - "443:443"
    volumes:
      - web:/var/www/html
    restart: always
  wordpress:
    container_name: wordpress
    image: wordpress:6.8.3
    build: requirements/wordpress
    networks:
      - web
      - database
    volumes:
      - web:/var/www/html
    restart: always
    secrets:
      - database_name
      - database_user_name
      - database_user_password
    env_file: .env
    depends_on:
      - mariadb
      - nginx

networks:
  database:
    driver: bridge
  web:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: ../data/database
      o: bind
  web:
    driver: local
    driver_opts:
      type: none
      device: ../data/web
      o: bind

secrets:
  database_name:
    file: ${DATABASE_NAME_SECRET_PATH}
  database_user_name:
    file: ${DATABASE_USER_NAME_SECRET_PATH}
  database_user_password:
    file: ${DATABASE_USER_PASSWORD_SECRET_PATH}
  # website_admin_email:
  #   file: ${WEBSITE_ADMIN_EMAIL_SECRET_PATH}
  # website_admin_password:
  #   file: ${WEBSITE_ADMIN_PASSWORD_SECRET_PATH}
  # website_admin_user:
  #   file: ${WEBSITE_ADMIN_USER_SECRET_PATH}
  # website_author_password:
  #   file: ${WEBSITE_AUTHOR_PASSWORD_SECRET_PATH}
  # ftp_user:
  #   file: ${FTP_USER_SECRET_PATH}
  # ftp_password:
  #   file: ${FTP_PASSWORD_SECRET_PATH}